maxFoodHistory: 10
food-values:
  APPLE: 4
  GOLDEN_APPLE: 4
  ENCHANTED_GOLDEN_APPLE: 4
  MELON_SLICE: 2
  SWEET_BERRIES: 2
  GLOW_BERRIES: 2
  CHORUS_FRUIT: 4
  CARROT: 3
  GOLDEN_CARROT: 6
  POTATO: 1
  BAKED_POTATO: 5
  POISONOUS_POTATO: 1
  BEETROOT: 1
  DRIED_KELP: 1
  BEEF: 3
  COOKED_BEEF: 8
  PORKCHOP: 3
  COOKED_PORKCHOP: 8
  CHICKEN: 2
  COOKED_CHICKEN: 6
  RABBIT: 3
  COOKED_RABBIT: 5
  MUTTON: 2
  COOKED_MUTTON: 6
  ROTTEN_FLESH: 4
  SPIDER_EYE: 1
  COD: 1
  COOKED_COD: 5
  SALMON: 2
  COOKED_SALMON: 6
  TROPICAL_FISH: 1
  PUFFERFISH: 1
  BREAD: 5
  CAKE: 14
  PUMPKIN_PIE: 8
  COOKIE: 2
  MUSHROOM_STEW: 6
  RABBIT_STEW: 10
  SUSPICIOUS_STEW: 6
  BEETROOT_SOUP: 6
  HONEY_BOTTLE: 6