name: HerbsOfLife
version: '1.0'
main: org.thrill12.herbsOfLife.HerbsOfLife
api-version: '1.21'
authors: [ Andrei Patea ]

commands:
  hol:
    description: Base command for the plugin
    usage: /hol <reload|reset|showHistory>
    permission: hol.admin